apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-metrics-config
  namespace: amazon-cloudwatch
data:
  config.yaml: |
    metrics:
      namespace: "EKS/CustomMetrics"
      metrics_collected:
        statsd:
          service_address: ":8125"
          metrics_collection_interval: 60
          metrics_aggregation_interval: 300
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-metrics-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-metrics
  template:
    metadata:
      labels:
        app: custom-metrics
    spec:
      containers:
      - name: app
        image: nginx:alpine
        ports:
        - containerPort: 80
        env:
        - name: STATSD_HOST
          value: "cloudwatch-agent.amazon-cloudwatch.svc.cluster.local"
        - name: STATSD_PORT
          value: "8125"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: custom-metrics-service
spec:
  selector:
    app: custom-metrics
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer