server:
  service:
    type: LoadBalancer
  persistentVolume:
    enabled: true
    size: 8Gi

alertmanager:
  enabled: false

pushgateway:
  enabled: false

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true