---
- name: Update kubeconfig for EKS cluster
  shell: aws eks update-kubeconfig --region {{ aws_region }} --name {{ eks_cluster_name }}
  environment:
    AWS_DEFAULT_REGION: "{{ aws_region }}"

- name: Generate Apache Kubernetes manifest
  template:
    src: apache-deployment.yaml.j2
    dest: /tmp/apache-deployment.yaml

- name: Deploy Apache to EKS cluster
  kubernetes.core.k8s:
    state: present
    src: /tmp/apache-deployment.yaml
    wait: true
    wait_condition:
      type: Available
      status: "True"
    wait_timeout: 300

- name: Get Apache service details
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Service
    name: "{{ apache_app_name }}-service"
    namespace: "{{ apache_namespace }}"
  register: apache_service

- name: Display Apache service URL
  debug:
    msg: "Apache web server deployed. LoadBalancer URL: {{ apache_service.resources[0].status.loadBalancer.ingress[0].hostname | default('Pending...') }}"