---
- name: Update kubeconfig for EKS cluster
  shell: aws eks update-kubeconfig --region {{ aws_region }} --name {{ eks_cluster_name }}
  environment:
    AWS_DEFAULT_REGION: "{{ aws_region }}"

- name: Generate Apache Kubernetes manifest
  template:
    src: apache-deployment.yaml.j2
    dest: /tmp/apache-deployment.yaml

- name: Deploy Apache to EKS cluster
  shell: kubectl apply -f /tmp/apache-deployment.yaml

- name: Check deployment status
  shell: kubectl get deployment {{ apache_app_name }} -n {{ apache_namespace }}
  register: deployment_status
  ignore_errors: true

- name: Check service status
  shell: kubectl get service {{ apache_app_name }}-service -n {{ apache_namespace }}
  register: service_status
  ignore_errors: true

- name: Display Apache deployment status
  debug:
    msg: |
      Apache web server deployment initiated.
      Deployment: {{ deployment_status.stdout_lines | default(['Not found']) | join(' ') }}
      Service: {{ service_status.stdout_lines | default(['Not found']) | join(' ') }}
      Note: If nodes are not ready, deployment will be pending until nodes are available.