---
- name: Update kubeconfig for EKS cluster
  shell: aws eks update-kubeconfig --region {{ aws_region }} --name {{ eks_cluster_name }}
  environment:
    AWS_DEFAULT_REGION: "{{ aws_region }}"

- name: Generate Apache Kubernetes manifest
  template:
    src: apache-deployment.yaml.j2
    dest: /tmp/apache-deployment.yaml

- name: Deploy Apache to EKS cluster
  shell: kubectl apply -f /tmp/apache-deployment.yaml

- name: Check deployment status
  shell: kubectl get deployment {{ apache_app_name }} -n {{ apache_namespace }}
  register: deployment_status
  ignore_errors: true

- name: Check service status
  shell: kubectl get service {{ apache_app_name }}-service -n {{ apache_namespace }}
  register: service_status
  ignore_errors: true

- name: Get LoadBalancer external IP
  shell: kubectl get service {{ apache_app_name }}-service -n {{ apache_namespace }} -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'
  register: lb_hostname
  ignore_errors: true

- name: Display Apache access information
  debug:
    msg: |
      Apache web server deployment status:
      Deployment: {{ deployment_status.stdout_lines | default(['Not found']) | join(' ') }}
      Service: {{ service_status.stdout_lines | default(['Not found']) | join(' ') }}
      
      ACCESS INFORMATION:
      - Cluster IP (internal only): 172.20.40.139:80
      - LoadBalancer URL: {{ lb_hostname.stdout | default('Still pending - wait for nodes to be ready') }}
      - NodePort: Use any worker node IP with port 30159
      
      Note: Wait for EXTERNAL-IP to show actual hostname, then use that URL to access Apache.