---
- name: Deploy Application Only
  hosts: localhost
  gather_facts: false
  
  vars:
    env_name: "{{ environment | default('aws-test') }}"
    aws_region: "{{ aws_region | default('us-east-2') }}"
    eks_cluster_name: "eks-{{ env_name }}"

  tasks:
    - name: Update kubeconfig
      shell: aws eks update-kubeconfig --region {{ aws_region }} --name {{ eks_cluster_name }}
      
    - name: Wait for nodes to be ready
      shell: kubectl wait --for=condition=Ready node --all --timeout=600s
      register: nodes_ready
      ignore_errors: true
      
    - name: Deploy Apache application
      include_role:
        name: apache
      when: nodes_ready.rc == 0
      
    - name: Show cluster status if nodes not ready
      shell: |
        echo "=== CLUSTER STATUS ==="
        kubectl get nodes -o wide
        kubectl get pods --all-namespaces
        echo "======================"
      when: nodes_ready.rc != 0