---
- name: Fix EKS Cluster Issues
  hosts: localhost
  gather_facts: false
  
  vars:
    env_name: "{{ environment | default('aws-test') }}"
    aws_region: "{{ aws_region | default('us-east-2') }}"
    eks_cluster_name: "eks-{{ env_name }}"

  tasks:
    - name: Delete existing CloudFormation stacks if needed
      shell: |
        aws cloudformation delete-stack --stack-name eksctl-{{ eks_cluster_name }}-cluster --region {{ aws_region }} || true
        aws cloudformation delete-stack --stack-name eksctl-{{ eks_cluster_name }}-nodegroup-ng-{{ env_name }} --region {{ aws_region }} || true
      ignore_errors: true
      
    - name: Wait for stack deletion
      shell: |
        aws cloudformation wait stack-delete-complete --stack-name eksctl-{{ eks_cluster_name }}-cluster --region {{ aws_region }} || true
      ignore_errors: true
      
    - name: Create cluster with simple config
      shell: |
        eksctl create cluster \
          --name {{ eks_cluster_name }} \
          --region {{ aws_region }} \
          --nodegroup-name ng-{{ env_name }} \
          --node-type t3.medium \
          --nodes 2 \
          --nodes-min 1 \
          --nodes-max 3 \
          --managed \
          --with-oidc \
          --ssh-access=false
      async: 2400
      poll: 60
      
    - name: Verify cluster
      shell: kubectl get nodes
      register: nodes_check
      retries: 10
      delay: 30
      until: nodes_check.rc == 0