---
- name: Troubleshoot Apache Deployment
  hosts: localhost
  gather_facts: false
  
  vars:
    env_name: "{{ environment | default('aws-test') }}"
    aws_region: "{{ aws_region | default('us-east-2') }}"
    eks_cluster_name: "eks-{{ env_name }}"

  tasks:
    - name: Update kubeconfig
      shell: aws eks update-kubeconfig --region {{ aws_region }} --name {{ eks_cluster_name }}
      
    - name: Check nodes
      shell: kubectl get nodes -o wide
      register: nodes
      
    - name: Check pods
      shell: kubectl get pods -n default -o wide
      register: pods
      
    - name: Check services
      shell: kubectl get svc -n default
      register: services
      
    - name: Check pod logs
      shell: kubectl logs -l app=apache-web -n default --tail=50
      register: logs
      ignore_errors: true
      
    - name: Check pod events
      shell: kubectl get events -n default --sort-by='.lastTimestamp'
      register: events
      
    - name: Display troubleshooting info
      debug:
        msg: |
          🔍 TROUBLESHOOTING INFORMATION:
          
          📊 NODES:
          {{ nodes.stdout }}
          
          🚀 PODS:
          {{ pods.stdout }}
          
          🌐 SERVICES:
          {{ services.stdout }}
          
          📝 POD LOGS:
          {{ logs.stdout | default('No logs available') }}
          
          ⚠️ EVENTS:
          {{ events.stdout }}