---
- name: Validate Deployment Success
  hosts: localhost
  gather_facts: false
  
  vars:
    env_name: "{{ environment | default('aws-test') }}"
    aws_region: "{{ aws_region | default('us-east-2') }}"
    eks_cluster_name: "eks-{{ env_name }}"

  tasks:
    - name: Update kubeconfig
      shell: aws eks update-kubeconfig --region {{ aws_region }} --name {{ eks_cluster_name }}
      
    - name: Test LoadBalancer connectivity
      uri:
        url: "http://{{ ansible_env.LB_URL | default('') }}"
        method: GET
        timeout: 10
      register: lb_test
      ignore_errors: true
      when: ansible_env.LB_URL is defined
      
    - name: Get final status
      shell: |
        echo "=== FINAL VALIDATION ==="
        kubectl get nodes
        kubectl get pods -n default
        kubectl get svc -n default
        echo "========================"
      register: final_status
      
    - name: Display validation results
      debug:
        msg: |
          🎯 DEPLOYMENT VALIDATION COMPLETE!
          
          {{ final_status.stdout }}
          
          ✅ Your application is successfully deployed and accessible!