# EKS Cluster Configuration
cluster_name: "devops-eks-cluster"
region: "us-west-2"
kubernetes_version: "1.28"

# VPC Configuration
vpc_cidr: "10.0.0.0/16"
public_subnet_cidrs:
  - "10.0.1.0/24"
  - "10.0.2.0/24"
private_subnet_cidrs:
  - "10.0.3.0/24"
  - "10.0.4.0/24"

# Node Group Configuration
node_group_name: "worker-nodes"
node_instance_type: "t3.medium"
node_desired_capacity: 2
node_min_size: 1
node_max_size: 4

# CloudWatch Configuration
enable_cloudwatch: true
cloudwatch_log_retention: 7