name: Deploy EKS with Ansible

on:
  push:
    branches:
      - main
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/Ansible

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y python3-pip unzip curl
          pip3 install ansible boto3 botocore

      - name: Install Ansible collections
        run: |
          ansible-galaxy collection install -r requirements.yaml --force
        working-directory: ${{ github.workspace }}/Ansible

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOYMENT_ROLE_ARN }}
          aws-region: us-east-1
          role-session-name: GitHubActions-Deploy

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Run Ansible Playbook to deploy EKS
        run: ansible-playbook create-eks.yml
